name: joshua-ives
favicon: null
layout_spectrum: 0.9204655806533992
typography_spectrum: 0.006614391226321459
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dce8f0'
    - '#d7bcaa'
    - '#7e7c58'
    - '#1b2630'
    - '#525646'
  brandStrength: 0.5
  lightness: 0.4280335318762809
  saturation: 0.38210962084122
  rhythmicContrast: 0.29668343788944185
purpose: []
